services:
  app:
    build: .
    container_name: prod-yam_notification-app
    env_file:
      - .env
#    ports:
#      - '3013:3000'
    networks:
#      - traefik-realt
      - yam-notifs
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.dashboard-prod.rule=Host(`dashboard.realt.community`)"
#      - "traefik.http.routers.dashboard-prod.entrypoints=websecure"
    restart: always

  db:
    image: mariadb:lts
    container_name: prod-yam_notification-db
    environment:
      - "MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MARIADB_USER=${MYSQL_USER}"
      - "MARIADB_PASSWORD=${MYSQL_PASSWORD}"
      - "MARIADB_DATABASE=${MYSQL_DATABASE}"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
#    ports:
#      - "3306:3306"
    networks:
      - yam-notifs
    restart: always
    
networks:
  yam-notifs:
#  traefik-realt:
#    external: true
